### ISSUE TITLE
ValueError: Namespace AppIndicator3 not available

### ISSUE THREAD

**Issue by akwala** [NoXPhasma/sshplus#2]
The following started happening presumably after an update of my venv that runs Python 3.8.5. The relevant dependency requirements are satisfied AFAICT. Can anyone else reproduce this?

```
$ python /path/to/sshplus.py
Traceback (most recent call last):
  File "/path/to/sshplus.py", line 37, in <module>
    gi.require_version("AppIndicator3", "0.1")
  File "/path/to/venv/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

$ python --version
Python 3.8.5

$ pip install pycairo
Requirement already satisfied: pycairo in ./lib/python3.8/site-packages (1.19.1)

$ pip install PyGObject
Requirement already satisfied: PyGObject in ./lib/python3.8/site-packages (3.36.1)
Requirement already satisfied: pycairo>=1.11.1 in ./lib/python3.8/site-packages (from PyGObject) (1.19.1)
```

**Comment by NoXPhasma** [comment]
I can not reproduce this, also with python 3.8.5. What distribution are you running?

**Comment by akwala** [comment]
> What distribution are you running?

Kubuntu 18.04

**Comment by NoXPhasma** [comment]
Try installing `libappindicator3-1` and `gir1.2-appindicator3-0.1` with `apt`.

**Comment by akwala** [comment]
> Try installing `libappindicator3-1` and `gir1.2-appindicator3-0.1` with `apt`.

They are installed, though they shouldn't come into play since I'm using a virtual environment.

```
libappindicator3-1 is already the newest version (12.10.1+18.04.20180322.1-0ubuntu1).
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+18.04.20180322.1-0ubuntu1).
```

**Comment by NoXPhasma** [comment]
Make sure both are available in the virtual environment, otherwise I have no clue what is causing this for you.

**Comment by akwala** [comment]
> Make sure both are available in the virtual environment, otherwise I have no clue what is causing this for you.

`pycairo` and `PyGObject` form the equivalent in the venv. I don't know if anything else is needed. It's a weird one.

**Comment by akwala** [comment]
I'm closing this because this isn't an issue with `sshplus`.
